# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnsave_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnsave_app.Location')),
            ],
        ),
    ]
