# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnsave_app', '0002_detectedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
