# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnsave_app', '0003_auto_20160416_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
