# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnsave_app', '0004_auto_20160416_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
